import { StyleSheet } from 'react-native';
import AppColor from '../../../../helpers/AppColor';
import { PopinsFont } from '../../../../helpers/Fonts';
import sizeHelper, { FontSizes, Spacing } from '../../../../helpers/sizeHelper';
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: AppColor.white,
  },
  infoContainer: {
    paddingHorizontal: 16,
    backgroundColor: AppColor.white,
    paddingBottom: 100,
  },
  bigImage: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  scrollContainer: {
    paddingRight: 10,
  },
  propertyImage: {
    height: 211,
    width: sizeHelper.screenWidth - 50,
    borderRadius: 12,
  },
  sectionTitle: {
    fontSize: FontSizes.s,
    fontFamily: PopinsFont.regular,
    color: '#6A6A6A',
    marginVertical: 10,
    lineHeight: Spacing.l,
    marginLeft: 5,
  },
  line: {
    height: 1,
    backgroundColor: '#000000',
    width: '25%',
    alignSelf: 'flex-start',
  },
  dateView: { marginVertical: 5 },
  dateText: {
    color: '#888888',
    fontFamily: PopinsFont.regular,
    fontSize: FontSizes.s,
    lineHeight: Spacing.l,
    textAlign: 'left',
  },
  descriptionRow: {
    alignItems: 'center',
    marginVertical: 5,
  },
  section: {
    backgroundColor: '#FFF',
    borderColor: '#E1E1E1',
    borderWidth: 1,
    borderRadius: 12,
    overflow: 'hidden',
  },
  propertyRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  rowContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  detailRow: {
    paddingHorizontal: Spacing.s,
    paddingVertical: Spacing.xs,
    borderBottomWidth: 1,
    borderBottomColor: '#E1E1E1',
  },
  starRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  detailLabel: {
    fontSize: 16,
    fontFamily: PopinsFont.regular,
    color: '#6A6A6A',
    lineHeight: Spacing.xl,
  },
  detailValue: {
    fontSize: FontSizes.m,
    lineHeight: Spacing.xl,
    fontFamily: PopinsFont.medium,
    color: '#2A2A2A',
    marginTop: 10,
  },
  smsIconContainer: {
    backgroundColor: '#F7F7F7',
    borderRadius: 100,
    height: 40,
    width: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  reviewContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  documentItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F7F7F7',
    borderWidth: 1,
    borderColor: '#E1E1E1',
    borderRadius: 12,
    padding: Spacing.s,
    justifyContent: 'space-between',
    marginVertical: 5,
  },
  documentText: {
    fontSize: FontSizes.m,
    fontFamily: PopinsFont.regular,
    color: '#2A2A2A',
    lineHeight: Spacing.xl,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  row2: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  stars: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  sideIcon: { height: 16, width: 16 },

  header: {
    backgroundColor: AppColor.white,
    width: '100%',
    paddingVertical: Spacing.s,
    alignSelf: 'center',
  },
  nameRow: {
    marginLeft: 5,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  tag: {
    height: Spacing.xl5,
    width: 90,
    borderRadius: Spacing.xl7,
    paddingVertical: Spacing.xs,
    paddingHorizontal: Spacing.x,
    backgroundColor: '#F7F7F7',
    borderWidth: 1,
    borderColor: '#E1E1E1',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
  },

  title: {
    fontSize: FontSizes.xl,
    lineHeight: FontSizes.xl4,
    fontFamily: PopinsFont.medium,
    color: AppColor.textColor,
  },

  highlight: {
    color: '#009FD9',
    fontSize: FontSizes.xl,
    lineHeight: FontSizes.xl4,
    fontFamily: PopinsFont.medium,
  },
  jobIdRow: {
    alignItems: 'cneter',
    marginVertical: 5,
    flexDirection: 'row',
    gap: 5,
    marginLeft: 5,
  },
  jobIdLabel: {
    fontSize: FontSizes.s,
    fontFamily: PopinsFont.regular,
    color: '#555555',
    lineHeight: Spacing.l,
  },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: AppColor.white,
    paddingVertical: Spacing.s,
    paddingHorizontal: Spacing.l,
    alignItems: 'center',
  },
  backIconContainer: {
    backgroundColor: '#F1F1F1',
    height: Spacing.xl6,
    width: Spacing.xl6,
    borderRadius: Spacing.s,
    justifyContent: 'center',
    alignItems: 'center',
  },
  leftIcon: { height: 20, width: 20 },
  globe: { height: 16, width: 16 },
  public: {
    fontFamily: PopinsFont.medium,
    fontSize: FontSizes.s,
    lineHeight: FontSizes.s,
    color: '#2A2A2A',
  },
  infoView: {
    width: '100%',
    alignSelf: 'center',
  },
  infoTouch: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  hideText: {
    color: '#2A2A2A',
    fontFamily: PopinsFont.regular,
    fontSize: FontSizes.s,
    lineHeight: Spacing.l,
  },
  detailsBox: {
    backgroundColor: '#FFF',
    borderColor: '#E1E1E1',
    borderWidth: 1,
    width: '100%',
    alignSelf: 'center',
    borderRadius: Spacing.s,
    marginBottom: 12,
    paddingVertical: 14,
    paddingHorizontal: Spacing.s,
  },
  text: {
    color: '#2A2A2A',
    fontFamily: PopinsFont.regular,
    fontSize: FontSizes.m,
    lineHeight: Spacing.xl,
    textAlign: 'left',
    marginTop: 12,
  },
  img: { height: 50, width: 50, borderRadius: 100 },
  copyIcon: { height: 12, width: 12, top: 3 },

  verifiedIcon: { height: 16, width: 16, left: 3 },
  messageIcon: { height: 20, width: 20 },
  curvedIcon: { height: 11, width: 11, top: 5, left: 3 },
  imageCountContainer: {
    position: 'absolute',
    bottom: 12,
    right: 15,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: Spacing.s,
    paddingVertical: 8,
    borderRadius: Spacing.s,
    gap: 10,
    height: Spacing.xl5,
  },

  imageCountText: {
    color: '#2A2A2A',
    fontSize: FontSizes.s,
    fontFamily: PopinsFont.regular,
    lineHeight: Spacing.l,
  },
  emptyImageView: {
    backgroundColor: '#F1F1F1',
    borderRadius: Spacing.l,
    alignSelf: 'flex-start',
    paddingHorizontal: Spacing.xs,
    paddingVertical: Spacing.xxs,
    marginBottom: 12,
    width: '100%',
    height: 220,
    alignItems: 'center',
    justifyContent: 'center',
  },
  nameContainer: {
    backgroundColor: AppColor.primaryBlue,
    height: 50,
    width: 50,
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  userName: {
    color: '#FFF',
    fontSize: FontSizes.l,
    fontFamily: PopinsFont.semiBold,
    lineHeight: Spacing.l,
    textAlign: 'center',
  },
});
export default styles;
