import { StyleSheet } from 'react-native';
import AppColor from '../../../helpers/AppColor';
import { PopinsFont } from '../../../helpers/Fonts';
import { FontSizes, Spacing } from '../../../helpers/sizeHelper';

const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: AppColor.popUpBackgroundColor,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  modalContainer: {
    backgroundColor: '#FFF',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    maxHeight: '90%',
    paddingVertical: 15,
    width: '100%',
  },

  jobDetailsCard: {
    backgroundColor: '#FFF',
    borderRadius: 12,
    paddingHorizontal: Spacing.s,
    paddingVertical: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#E1E1E1',
    width: '100%',
  },
  jobTitleRow: {
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    // marginBottom: 8,
    flexDirection: 'row',
    width: '100%',
  },
  title: {
    color: '#2A2A2A',
    fontSize: FontSizes.m,
    fontFamily: PopinsFont.regular,
    lineHeight: Spacing.xl,
  },

  highlight: {
    color: '#009FD9',
    fontSize: FontSizes.m,
    fontFamily: PopinsFont.regular,
    lineHeight: Spacing.l,
  },

  budgetText: {
    fontSize: FontSizes.s,
    color: '#6A6A6A',
    fontFamily: PopinsFont.regular,
    lineHeight: Spacing.l,
  },
  budget: {
    fontSize: FontSizes.m,
    color: '#2A2A2A',
    fontFamily: PopinsFont.medium,
    lineHeight: Spacing.l,
  },
  infoNote: {
    backgroundColor: '#E6F6FC',
    borderWidth: 1,
    borderColor: '#009FD9',
    paddingVertical: 12,
    paddingHorizontal: 15,
    borderRadius: 8,
    width: '100%',
    // marginBottom: 20,
  },
  infoNoteText: {
    fontSize: FontSizes.m,
    color: '#005F82',
    lineHeight: Spacing.l,
    fontFamily: PopinsFont.regular,
    textAlign: 'left',
    right: 7,
  },
  billingCard: {
    backgroundColor: '#F7F7F7',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 10,

    width: '100%',
  },
  billingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 5,
  },
  billingLabel: {
    fontSize: FontSizes.s,
    color: '#6A6A6A',
    fontFamily: PopinsFont.regular,
    lineHeight: Spacing.l,
  },
  billingValue: {
    fontSize: FontSizes.m,
    color: '#2A2A2A',
    fontFamily: PopinsFont.regular,
    lineHeight: Spacing.l,
  },

  amountInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 12,
    padding: Spacing.s,
    backgroundColor: '#F1F1F1',
    height: 44,
    overflow: 'hidden',
  },
  currencySymbol: {
    fontSize: FontSizes.m,
    color: '#6A6A6A',
    marginRight: 4,
    fontFamily: PopinsFont.regular,
    lineHeight: Spacing.l,
  },
  amountInput: {
    fontSize: FontSizes.m,
    color: '#6A6A6A',
    paddingVertical: 12,
    fontFamily: PopinsFont.regular,
    lineHeight: Spacing.l,
    backgroundColor: 'red',
    width: '100%',
    backgroundColor: '#F1F1F1',
    height: 50,
    marginLeft: 5,
    textAlignVertical: 'center',
  },

  textArea: {
    borderRadius: 12,
    padding: 10,
    minHeight: 100,
    textAlignVertical: 'top',
    backgroundColor: '#F1F1F1',
    height: 80,
    color: '#6A6A6A',
    fontFamily: PopinsFont.regular,
    fontSize: FontSizes.s,
  },

  buttonsContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 12,
    marginTop: 16,
  },
  button: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 40,
    minWidth: 110,
    alignItems: 'center',
  },
  cancelButton: {
    backgroundColor: '#F0F3F8',
    borderWidth: 1,
    borderColor: '#DFE6EF',
  },
  cancelButtonText: {
    fontWeight: '600',
    color: '#334E6E',
  },
  terminateButton: {
    backgroundColor: '#E03A3A',
    shadowColor: '#E03A3A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 2,
  },
  terminateButtonText: {
    fontWeight: '600',
    color: '#FFFFFF',
  },
  tag: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E1E1E1',
    backgroundColor: '#FFF',
    borderRadius: Spacing.s,
    paddingVertical: Spacing.xxs,
    paddingHorizontal: Spacing.xs,
    width: 75,
    alignSelf: 'flex-start',
    marginVertical: 5,
    gap: 5,
  },

  public: {
    color: '#555555',
    fontFamily: PopinsFont.regular,
    fontSize: FontSizes.s,
    lineHeight: Spacing.m,
  },
  infoBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 5,
  },
  proposed: {
    color: '#6A6A6A',
    fontFamily: PopinsFont.regular,
    fontSize: FontSizes.s,
    lineHeight: Spacing.l,
    marginVertical: 10,
  },
  reason: {
    color: '#6A6A6A',
    fontFamily: PopinsFont.regular,
    lineHeight: Spacing.l,
    fontSize: FontSizes.s,
    marginBottom: 5,
  },
  termsView: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    gap: 5,
    marginTop: 20,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  accept: {
    color: '#6A6A6A',
    fontSize: FontSizes.s,
    fontFamily: PopinsFont.regular,
    lineHeight: Spacing.l,
  },
  termsText: {
    top: 5,
    color: '#CC7120',
    fontSize: FontSizes.s,
    fontFamily: PopinsFont.regular,
    lineHeight: Spacing.l,
  },
  bill: {
    color: '#6A6A6A',
    fontFamily: PopinsFont.regular,
    fontSize: FontSizes.s,
    lineHeight: Spacing.l,
    marginVertical: 10,
  },
});
export default styles;
