import { StyleSheet } from 'react-native';
import { PopinsFont } from '../../../../helpers/Fonts';
import { FontSizes, Spacing } from '../../../../helpers/sizeHelper';
import AppColor from '../../../../helpers/AppColor';
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFF',
  },
  secondContainer: { flex: 1 },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: AppColor.white,
    paddingVertical: Spacing.s,
    paddingHorizontal: 18,
    alignItems: 'center',
  },
  backIconContainer: {
    backgroundColor: '#F1F1F1',
    height: Spacing.xl6,
    width: Spacing.xl6,
    borderRadius: Spacing.s,
    justifyContent: 'center',
    alignItems: 'center',
  },
  leftIcon: { height: 20, width: 20 },
  row: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 5,
  },
  globe: { height: 16, width: 16 },
  public: {
    fontFamily: PopinsFont.medium,
    fontSize: FontSizes.s,
    lineHeight: FontSizes.s,
    color: '#2A2A2A',
  },
  inProgress: {
    fontFamily: PopinsFont.medium,
    fontSize: FontSizes.s,
    lineHeight: FontSizes.l,
    color: '#2A2A2A',
  },
  arrow: { width: 14, height: 8 },

  tag: {
    height: Spacing.xl5,
    width: 75,
    borderRadius: Spacing.s,
    paddingVertical: Spacing.xs,
    paddingHorizontal: Spacing.x,
    backgroundColor: '#F7F7F7',
    borderWidth: 1,
    borderColor: '#E1E1E1',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 5,
  },
  tag2: {
    height: Spacing.xl5,
    width: 140,
    borderRadius: Spacing.s,
    paddingVertical: Spacing.xs,
    paddingHorizontal: Spacing.x,
    backgroundColor: '#F7F7F7',
    borderWidth: 1,
    borderColor: '#E1E1E1',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
  },

  sideIcon: { height: 16, width: 16 },
  boxLabel: {
    color: '#6A6A6A',
    fontFamily: PopinsFont.regular,
    fontSize: FontSizes.s,
    lineHeight: Spacing.l,
  },
  boxValue: {
    color: '#2A2A2A',
    fontFamily: PopinsFont.medium,
    fontSize: FontSizes.m,
    lineHeight: Spacing.l,
  },
  statsView: {
    backgroundColor: '#F1F1F1',
    borderWidth: 1,
    borderColor: '#E1E1E1',
    borderRadius: 10,
    width: '90%',
    alignSelf: 'center',
    paddingHorizontal: 5,
    paddingVertical: 10,
    marginBottom: 12,
  },
  innerView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  innerBox: {
    backgroundColor: '#FFF',
    width: 184,
    height: 104,
    borderRadius: Spacing.s,
    padding: Spacing.s,
    justifyContent: 'space-between',
  },
  box: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  boxIcon: { height: 20, width: 20 },
  value: {
    fontFamily: PopinsFont.medium,
    fontSize: FontSizes.xl4,
    lineHeight: FontSizes.xl4,
  },
  text: {
    fontFamily: PopinsFont.medium,
    fontSize: FontSizes.s,
    color: AppColor.textColor,
    lineHeight: Spacing.l,
  },
  box1: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  view1: {
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 12,
    paddingHorizontal: 18,
  },
  img: { height: 100, width: 100, marginBottom: 12 },
  view2: {
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  view3: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    marginBottom: 4,
  },
  name: {
    color: '#2A2A2A',
    fontFamily: PopinsFont.medium,
    fontSize: FontSizes.l,
    textAlign: 'center',
    lineHeight: Spacing.xxl,
  },
  join: {
    color: '#6A6A6A',
    fontFamily: PopinsFont.regular,
    fontSize: FontSizes.s,
    lineHeight: Spacing.l,
  },
  infoView: {
    marginBottom: 12,
    width: '95%',
    alignSelf: 'center',
    paddingHorizontal: 18,
  },
  infoTouch: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  hideText: {
    color: '#6A6A6A',
    fontFamily: PopinsFont.medium,
    fontSize: FontSizes.s,
    lineHeight: Spacing.l,
  },
  detailsBox: {
    backgroundColor: '#FFF',
    borderColor: '#E1E1E1',
    borderWidth: 1,
    width: '90%',
    alignSelf: 'center',
    borderRadius: 12,
    marginBottom: 12,
  },
  boxView1: {
    padding: Spacing.s,
    borderBottomColor: '#E1E1E1',
    borderBottomWidth: 1,
  },
  content: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  memberText: {
    color: '#6A6A6A',
    fontFamily: PopinsFont.regular,
    fontSize: FontSizes.s,
    lineHeight: Spacing.l,
    textAlign: 'auto',
    paddingHorizontal: 18,
  },
  //   dropdown
  dropDowncontainer: {
    backgroundColor: '#FFF',
    paddingVertical: 10,
    width: '90%',
    alignSelf: 'center',
  },
  dropdown: {
    height: 44,
    borderColor: '#E1E1E1',
    borderWidth: 1,
    borderRadius: Spacing.s,
    paddingHorizontal: 8,
    backgroundColor: '#FFF',
    width: '100%',
  },
  placeholderStyle: {
    fontSize: FontSizes.s,
    lineHeight: Spacing.l,
    color: '#2A2A2A',
    fontFamily: PopinsFont.regular,
  },
  selectedTextStyle: {
    fontSize: 16,
  },
  iconStyle: {
    width: 20,
    height: 20,
  },
  content2: {
    flexDirection: 'row',
    paddingHorizontal: 5,
    paddingVertical: 10,
  },
  flatlistView: {
    flex: 1,
    backgroundColor: '#F1F1F1',
    borderTopLeftRadius: Spacing.xl,
    borderTopRightRadius: Spacing.xl,
    paddingHorizontal: Spacing.l,
    paddingTop: Spacing.l,
  },
  headingText: {
    fontFamily: PopinsFont.medium,
    fontSize: FontSizes.s,
    lineHeight: Spacing.l,
    color: AppColor.textColor,
    marginLeft: 5,
    marginBottom: 12,
  },
  flatlist: {
    flex: 1,
    position: 'relative',
  },
  footer: {
    backgroundColor: '#FFFFFF',
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginVertical: 10,
  },
  footerText: {
    color: '#6A6A6A',
    fontFamily: PopinsFont.regular,
    fontSize: FontSizes.s,
    lineHeight: FontSizes.l,
  },
  actionCard: {
    marginVertical: 5,
  },
  button: {
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    // marginBottom: 10,
    width: '97%',
    backgroundColor: '#FFF',
    borderColor: '#E1E1E1',
    borderWidth: 1,
    borderTopLeftRadius: Spacing.s,
    borderTopRightRadius: Spacing.s,
    paddingVertical: Spacing.s,
    paddingHorizontal: Spacing.l,
    flexDirection: 'row',
    gap: 10,
  },
  sideIcon: { height: 15, width: 15 },
  dot: {
    height: 11,
    width: 11,
    borderRadius: 10,
    backgroundColor: '#009FD9',
  },
  verified: { height: 21, width: 21 },
  flatlistContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
    width: '92%',
    alignSelf: 'center',
  },
});
export default styles;
