import React from 'react';
import {
  View,
  Text,
  ScrollView,
  Image,
  TouchableOpacity,
  ActivityIndicator,
} from 'react-native';
import styles from './style';

import Header from '../../../../components/Header';
import { PopinsFont } from '../../../../helpers/Fonts';
import { FontSizes, Spacing } from '../../../../helpers/sizeHelper';
import { CopyIcon } from '../../../../assets/svg';
import Button from '../../../../components/Button';

import Clipboard from '@react-native-clipboard/clipboard';
import { showToast } from '../../../../helpers/ToastConfig';
import AppColor from '../../../../helpers/AppColor';
import { handleCopyText } from '../../../../helpers/services';
const Design = props => {
  return (
    <View style={styles.container}>
      <Header showBackIcon title={'Enable 2FA'} navigation={props.navigation} />

      <ScrollView
        showsVerticalScrollIndicator={false}
        contentContainerStyle={styles.infoContainer}
      >
        <View style={styles.content}>
          <Text style={styles.text}>
            Copy the secret code to your authentication app on your mobile
            device. Then paste the two-factor verification code generated by
            your app below.
            <TouchableOpacity>
              <Text style={styles.text1}>Learn more.</Text>
            </TouchableOpacity>
          </Text>
        </View>
        <View style={styles.qrView}>
          {props.isLoading && (
            <View style={[styles.qr, { alignSelf: 'center' }]}>
              <ActivityIndicator
                size="large"
                color={AppColor.primaryBlue}
                style={{ marginTop: 80 }}
              />
            </View>
          )}
          {props.mfaData !== null && (
            <Image
              source={{ uri: props.mfaData.qrCode }}
              resizeMode="contain"
              style={styles.qr}
            />
          )}
        </View>
        {props.mfaData !== null && props?.mfaData?.manualEntryKey && (
          <View style={styles.helperText}>
            <Text style={[styles.text, { marginBottom: 12 }]}>
              Scan QR code or Copy Secret Code
            </Text>
            <View style={styles.idView}>
              <Text style={styles.idText}>
                {props?.mfaData?.manualEntryKey}
              </Text>

              <TouchableOpacity
                onPress={() => handleCopyText(props?.mfaData?.manualEntryKey)}
              >
                <CopyIcon style={styles.icon} fill={'#2A2A2A'} />
              </TouchableOpacity>
            </View>
          </View>
        )}
        {props.mfaData !== null &&
          Array.isArray(props.mfaData.recoveryCodes) &&
          props.mfaData.recoveryCodes.length > 0 && (
            <View
              style={{
                flexDirection: 'row',
                flexWrap: 'wrap',
                marginVertical: 12,
                paddingHorizontal: 16,
              }}
            >
              {props.mfaData.recoveryCodes.map((code, index) => (
                <View
                  key={index}
                  style={{
                    width: '50%', // 👈 2 per row
                    padding: 5,
                  }}
                >
                  <View
                    style={{
                      padding: 10,
                      borderWidth: 1,
                      borderRadius: 6,
                      alignItems: 'center',
                      backgroundColor: '#F7F7F7',
                      borderColor: '#E1E1E1',
                    }}
                  >
                    <Text style={styles.code}>{code}</Text>
                  </View>
                </View>
              ))}
              <Button
                text={'Copy Codes'}
                color={'#FFF'}
                fontFamily={PopinsFont.regular}
                fontSize={FontSizes.m}
                lineHeight={Spacing.xl}
                height={44}
                backgroundColor={'#009FD9'}
                borderWidth={1}
                borderColor={'#009FD9'}
                width={'100%'}
                borderRadius={Spacing.s}
                onPress={() => {
                  const allCodes = props.mfaData.recoveryCodes.join('\n');
                  handleCopyText(allCodes);
                }}
                marginVertical={12}
              />
            </View>
          )}
      </ScrollView>
      {props.mfaData !== null && (
        <View style={styles.button}>
          <Button
            text={'Cancel'}
            color={'#404040'}
            fontFamily={PopinsFont.regular}
            fontSize={FontSizes.m}
            lineHeight={Spacing.xl}
            height={44}
            backgroundColor={'#F7F7F7'}
            borderWidth={1}
            borderColor={'#E1E1E1'}
            width={'49%'}
            borderRadius={Spacing.s}
            onPress={() => props.navigation.navigate('Security')}
          />
          <Button
            text={'Next'}
            color={'#FFF'}
            fontFamily={PopinsFont.regular}
            fontSize={FontSizes.m}
            lineHeight={Spacing.xl}
            height={44}
            backgroundColor={'#009FD9'}
            borderWidth={1}
            borderColor={'#009FD9'}
            width={'49%'}
            borderRadius={Spacing.s}
            onPress={() => props.navigation.navigate('Enable2FAOTP')}
          />
        </View>
      )}
    </View>
  );
};

export default Design;
