import { StyleSheet } from 'react-native';
import { PopinsFont } from '../../../../helpers/Fonts';
import { FontSizes, Spacing } from '../../../../helpers/sizeHelper';
import AppColor from '../../../../helpers/AppColor';
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFF',
  },
  content: {
    flex: 1,
    backgroundColor: '#F1F1F1',
    borderTopLeftRadius: Spacing.l,
    borderTopRightRadius: Spacing.l,
  },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: AppColor.white,
    paddingVertical: Spacing.s,
    paddingHorizontal: Spacing.l,
    alignItems: 'center',
  },
  backIconContainer: {
    backgroundColor: '#F1F1F1',
    height: Spacing.xl6,
    width: Spacing.xl6,
    borderRadius: Spacing.s,
    justifyContent: 'center',
    alignItems: 'center',
  },
  leftIcon: { height: 20, width: 20 },
  row: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 5,
  },
  globe: { height: 16, width: 16 },
  public: {
    fontFamily: PopinsFont.medium,
    fontSize: FontSizes.s,
    lineHeight: FontSizes.s,
    color: '#2A2A2A',
  },
  inProgress: {
    fontFamily: PopinsFont.medium,
    fontSize: FontSizes.s,
    lineHeight: FontSizes.l,
    color: '#2A2A2A',
  },
  arrow: { width: 14, height: 8 },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: '#F1F1F1',
    borderWidth: 1,
    borderColor: '#E1E1E1',
    paddingHorizontal: 2,
    alignSelf: 'center',
    width: '90%',
    borderRadius: Spacing.s,
    padding: Spacing.xxs,
    height: Spacing.xl6,
  },
  tab: {
    width: '50%',
    backgroundColor: '#F1F1F1',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: Spacing.xs,
  },
  activeTab: {
    width: '50%',
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: Spacing.xs,
  },
  tabText: {
    fontSize: FontSizes.s,
    fontFamily: PopinsFont.regular,
    color: '#6A6A6A',
    lineHeight: Spacing.l,
  },
  activeTabText: {
    fontSize: FontSizes.s,
    fontFamily: PopinsFont.regular,
    color: '#2A2A2A',
    lineHeight: Spacing.l,
  },
  header: {
    backgroundColor: AppColor.white,
    // height: 80,
    width: '100%',
    paddingVertical: Spacing.s,
    paddingHorizontal: Spacing.m,
    alignSelf: 'center',
  },
  nameRow: {
    marginLeft: 5,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  tag: {
    height: Spacing.xl5,
    width: 90,
    borderRadius: Spacing.xl7,
    paddingVertical: Spacing.xs,
    paddingHorizontal: Spacing.x,
    backgroundColor: '#F7F7F7',
    borderWidth: 1,
    borderColor: '#E1E1E1',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
  },
  tag2: {
    height: Spacing.xl5,
    // width: 140,
    borderRadius: 12,
    paddingVertical: Spacing.xs,
    paddingHorizontal: Spacing.s,
    backgroundColor: '#F7F7F7',
    borderWidth: 1,
    borderColor: '#E1E1E1',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
  },
  title: {
    fontSize: FontSizes.xl,
    lineHeight: FontSizes.xl4,
    fontFamily: PopinsFont.medium,
    color: AppColor.textColor,
  },

  highlight: {
    color: '#009FD9',
    fontSize: FontSizes.xl,
    lineHeight: FontSizes.xl4,
    fontFamily: PopinsFont.medium,
  },
  jobIdRow: {
    alignItems: 'cneter',
    marginVertical: 5,
    flexDirection: 'row',
    gap: 5,
    marginLeft: 5,
  },
  jobIdLabel: {
    fontSize: FontSizes.s,
    fontFamily: PopinsFont.regular,
    color: '#555555',
    lineHeight: Spacing.l,
  },
  sideIcon: { height: 16, width: 16 },
  timerContainer: {
    backgroundColor: '#FFF',
    borderTopWidth: 1,
    borderTopColor: '#EFF0F4',
    paddingHorizontal: 16,
    // paddingVertical: 12,
  },
  timerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#E1E1E1',
    backgroundColor: '#FFFFFF',
  },

  timerValue: {
    fontSize: FontSizes.xxl,
    fontFamily: PopinsFont.medium,
    color: '#6A6A6A',
    lineHeight: Spacing.xxl,
  },
  buttonsView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
    paddingHorizontal: 16,
    gap: 5,
  },
  timeView: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    width: '50%',
  },
});
export default styles;
