import { StyleSheet } from 'react-native';
import AppColor from '../../../../helpers/AppColor';
import { PopinsFont } from '../../../../helpers/Fonts';
import { FontSizes, Spacing } from '../../../../helpers/sizeHelper';
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: AppColor.white,
  },
  infoContainer: {
    backgroundColor: AppColor.white,
  },

  sectionTitle: {
    fontSize: FontSizes.s,
    fontFamily: PopinsFont.regular,
    color: '#6A6A6A',
    marginVertical: 10,
    lineHeight: Spacing.l,
    marginLeft: 5,
  },
  line: {
    height: 1,
    backgroundColor: '#000000',
    width: '30%',
    alignSelf: 'flex-start',
  },

  descriptionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginVertical: 5,
  },
  section: {
    backgroundColor: '#FFF',
    borderColor: '#E1E1E1',
    borderWidth: 1,
    borderRadius: 12,
    overflow: 'hidden',
  },
  propertyRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  rowContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  detailRow: {
    paddingHorizontal: Spacing.s,
    paddingVertical: Spacing.xs,
    borderBottomWidth: 1,
    borderBottomColor: '#E1E1E1',
  },
  starRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  detailLabel: {
    fontSize: 16,
    fontFamily: PopinsFont.regular,
    color: '#6A6A6A',
    lineHeight: Spacing.l,
  },
  detailValue: {
    fontSize: FontSizes.m,
    lineHeight: Spacing.xl,
    fontFamily: PopinsFont.medium,
    color: '#2A2A2A',
    marginTop: 10,
  },
  smsIconContainer: {
    backgroundColor: '#F7F7F7',
    borderRadius: 100,
    height: 40,
    width: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  reviewContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  documentItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F7F7F7',
    borderWidth: 1,
    borderColor: '#E1E1E1',
    borderRadius: 12,
    padding: Spacing.s,
    justifyContent: 'space-between',
    marginVertical: 5,
  },
  documentText: {
    fontSize: FontSizes.m,
    fontFamily: PopinsFont.regular,
    color: '#2A2A2A',
    lineHeight: Spacing.xl,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  row2: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  stars: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  sideIcon: { height: 16, width: 16 },

  header: {
    backgroundColor: AppColor.white,
    width: '100%',
    paddingVertical: Spacing.s,
    alignSelf: 'center',
    paddingHorizontal: 16,
  },
  nameRow: {
    marginLeft: 5,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  tag: {
    height: Spacing.xl5,
    width: 90,
    borderRadius: Spacing.xl7,
    paddingVertical: Spacing.xs,
    paddingHorizontal: Spacing.x,
    backgroundColor: '#F7F7F7',
    borderWidth: 1,
    borderColor: '#E1E1E1',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
  },

  title: {
    fontSize: FontSizes.xl,
    lineHeight: FontSizes.xl4,
    fontFamily: PopinsFont.medium,
    color: AppColor.textColor,
  },

  highlight: {
    color: '#009FD9',
    fontSize: FontSizes.xl,
    lineHeight: FontSizes.xl4,
    fontFamily: PopinsFont.medium,
  },
  jobIdRow: {
    alignItems: 'cneter',
    marginVertical: 5,
    flexDirection: 'row',
    gap: 5,
    marginLeft: 5,
  },
  jobIdLabel: {
    fontSize: FontSizes.s,
    fontFamily: PopinsFont.regular,
    color: '#555555',
    lineHeight: Spacing.l,
  },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: AppColor.white,
    paddingVertical: Spacing.s,
    paddingHorizontal: Spacing.l,
    alignItems: 'center',
  },
  backIconContainer: {
    backgroundColor: '#FFECEC',
    height: Spacing.xl6,
    width: Spacing.xl6,
    borderRadius: Spacing.s,
    justifyContent: 'center',
    alignItems: 'center',
  },
  leftIcon: { height: 15, width: 15 },

  globe: { height: 16, width: 16 },
  public: {
    fontFamily: PopinsFont.medium,
    fontSize: FontSizes.s,
    lineHeight: FontSizes.s,
    color: '#2A2A2A',
  },
  //
  headingText: {
    fontFamily: PopinsFont.medium,
    fontSize: FontSizes.l,
    lineHeight: Spacing.l,
    color: AppColor.textColor,
    marginLeft: 5,
    marginBottom: 12,
  },
  label: {
    fontSize: FontSizes.s,
    fontFamily: PopinsFont.regular,
    color: '#6A6A6A',
    marginBottom: 8,
    lineHeight: Spacing.l,
  },
  imagePickerButton: {
    borderWidth: 2,
    borderColor: '#C3C3C3',
    borderRadius: 12,
    padding: 10,
    alignItems: 'center',
    backgroundColor: '#F7F7F7',
    borderStyle: 'dashed',
    height: 160,
    justifyContent: 'center',
    alignSelf: 'center',
    alignItems: 'center',
    width: '100%',
  },
  imagePickerText: {
    fontSize: FontSizes.m,
    lineHeight: Spacing.xl,
    fontFamily: PopinsFont.medium,
    color: '#6A6A6A',
    marginTop: 8,
    textAlign: 'center',
  },
  imagePickerNote: {
    fontSize: FontSizes.s,
    lineHeight: Spacing.l,
    fontFamily: PopinsFont.regular,
    color: '#6A6A6A',
    marginTop: 4,
  },
  imagesRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 12,
    gap: 8,
    paddingHorizontal: 10,
  },
  imageThumbnail: {
    width: 80,
    height: 80,
    borderRadius: 8,
    position: 'relative',
  },
  image: {
    width: '100%',
    height: '100%',
    borderRadius: 8,
  },
  removeImageBtn: {
    position: 'absolute',
    top: -6,
    right: -6,
    backgroundColor: '#F7F7F7',
    borderRadius: 12,
    width: 22,
    height: 22,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 4,
    borderColor: '#FFFFFF',
  },
  amountInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 12,
    padding: Spacing.s,
    backgroundColor: '#FFF',
    height: 44,
    overflow: 'hidden',
  },
  currencySymbol: {
    fontSize: FontSizes.m,
    color: '#6A6A6A',
    marginRight: 4,
    fontFamily: PopinsFont.regular,
    lineHeight: Spacing.l,
  },
  amountInput: {
    fontSize: FontSizes.m,
    color: '#6A6A6A',
    paddingVertical: 12,
    fontFamily: PopinsFont.regular,
    lineHeight: Spacing.l,
    backgroundColor: 'red',
    width: '100%',
    backgroundColor: '#FFF',
    height: 50,
    marginLeft: 5,
    textAlignVertical: 'center',
  },

  textArea: {
    borderRadius: 12,
    padding: 10,
    height: 130,
    textAlignVertical: 'top',
    backgroundColor: '#FFF',
    maxHeight: 150,
    color: '#6A6A6A',
    fontFamily: PopinsFont.regular,
    fontSize: FontSizes.s,
  },
  button: {
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
    width: '97%',
    backgroundColor: '#FFF',
    borderColor: '#E1E1E1',
    borderWidth: 1,
    borderTopLeftRadius: Spacing.s,
    borderTopRightRadius: Spacing.s,
    paddingVertical: Spacing.s,
    paddingHorizontal: Spacing.l,
  },
  mainView: {
    flex: 1,
    backgroundColor: '#F1F1F1',
    borderTopLeftRadius: Spacing.xl,
    borderTopRightRadius: Spacing.xl,
    padding: Spacing.l,
  },
  uploadImageView: {
    marginBottom: 20,
    marginLeft: 5,
  },
  uploadDocumentButtonView: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    paddingVertical: Spacing.s,
    paddingHorizontal: Spacing.xs,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  dateTime: {
    color: '#6A6A6A',
    fontFamily: PopinsFont.regular,
    fontSize: FontSizes.m,
    lineHeight: Spacing.xl,
    textAlign: 'left',
  },
  dateButton: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: Spacing.s,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  visitText: {
    color: '#2A2A2A',
    fontFamily: PopinsFont.medium,
    fontSize: FontSizes.l,
    lineHeight: Spacing.xl,
    textAlign: 'left',
  },
  visitView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 12,
    alignItems: 'center',
    height: 40,
  },
  feeText: {
    color: AppColor.primaryBlue,
    fontFamily: PopinsFont.regular,
    fontSize: FontSizes.s,
    width: '100%',
    marginLeft: 5,
    marginVertical: 5,
    lineHeight: Spacing.l,
    textAlign: 'left',
  },
});
export default styles;
