import { StyleSheet } from 'react-native';
import AppColor from '../../../../helpers/AppColor';
import { PopinsFont } from '../../../../helpers/Fonts';
import { FontSizes, Spacing } from '../../../../helpers/sizeHelper';
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: AppColor.white,
  },
  scrollContent: {
    flex: 1,
  },

  searchContainer: {
    backgroundColor: '#F1F1F1',
    borderRadius: Spacing.s,
    height: Spacing.xl6,
    paddingHorizontal: Spacing.s,
    paddingVertical: Spacing.xs,
    justifyContent: 'center',
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
  },
  input: {
    backgroundColor: '#F1F1F1',
    height: Spacing.xl6,
    paddingHorizontal: 10,
    width: '100%',
    fontFamily: PopinsFont.regular,
    fontSize: FontSizes.s,
    lineHeight: Spacing.l,
    color: AppColor.black,
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'left',
    borderRadius: Spacing.s,
  },
  actionCard: {
    marginVertical: 5,
  },
  flatlistView: {
    flex: 1,
    backgroundColor: '#F1F1F1',
    borderTopLeftRadius: Spacing.xl,
    borderTopRightRadius: Spacing.xl,
    paddingHorizontal: Spacing.l,
    paddingTop: Spacing.l,
  },
  flatlist: { flex: 1 },
  headingText: {
    fontFamily: PopinsFont.medium,
    fontSize: FontSizes.s,
    lineHeight: Spacing.s,
    color: AppColor.textColor,
    marginLeft: 5,
    marginBottom: 12,
  },
  footer: {
    backgroundColor: '#FFFFFF',
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginVertical: 10,
  },
  footerText: {
    color: '#6A6A6A',
    fontFamily: PopinsFont.regular,
    fontSize: FontSizes.s,
    lineHeight: FontSizes.l,
  },
  filterContainer: {
    alignItems: 'center',
    paddingHorizontal: 20,
    marginVertical: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  filterButton: {
    backgroundColor: '#FFF',
    borderColor: '#E1E1E1',
    borderWidth: 1,
    borderRadius: Spacing.s,
    padding: Spacing.s,
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  clearButton: {
    backgroundColor: '#FFECEC',
    borderColor: '#FFD7D8',
    borderWidth: 1,
    borderRadius: Spacing.s,
    padding: Spacing.s,
    justifyContent: 'center',
    alignItems: 'center',
  },
  clearText: {
    color: '#CC2D30',
    fontFamily: PopinsFont.regular,
    fontSize: FontSizes.m,
    lineHeight: Spacing.l,
  },
  filterIcon: { height: 20, width: 20 },
  filterText: {
    color: '#2A2A2A',
    fontFamily: PopinsFont.regular,
    fontSize: FontSizes.m,
    lineHeight: Spacing.l,
  },
  filterOptions: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 20,
  },
  text: {
    color: '#151515',
    fontSize: FontSizes.m,
    lineHeight: Spacing.xl,
    fontFamily: PopinsFont.regular,
    marginLeft: 5,
  },
  locationButton: {
    backgroundColor: '#E6F6FC',
    borderColor: '#CCECF7',
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    borderRadius: 100,
    padding: 5,
  },
  locationIcon: { height: 28, width: 28 },
  content: { paddingHorizontal: 20, marginTop: 10 },
  searchIconContainer: {
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingLeft: 10,
  },
  searchIcon: { height: 15, width: 15 },
  emptyView: {
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    gap: 10,
    height: 300,
    width: '100%',
  },
  noText: {
    color: '#6A6A6A',
    fontFamily: PopinsFont.regular,
    fontSize: FontSizes.s,
    lineHeight: Spacing.l,
    textAlign: 'center',
  },
});
export default styles;
