import { StyleSheet } from 'react-native';
import AppColor from '../../../../helpers/AppColor';
import { PopinsFont } from '../../../../helpers/Fonts';
import sizeHelper, { FontSizes, Spacing } from '../../../../helpers/sizeHelper';
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: AppColor.white,
  },
  infoContainer: {
    backgroundColor: AppColor.white,
  },

  button: {
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
    width: '97%',
    backgroundColor: '#FFF',
    borderColor: '#E1E1E1',
    borderWidth: 1,
    borderTopLeftRadius: Spacing.s,
    borderTopRightRadius: Spacing.s,
    paddingVertical: Spacing.s,
    paddingHorizontal: Spacing.l,
    flexDirection: 'row',
    gap: 10,
  },

  coverWrapper: {
    width: '100%',
    alignItems: 'center',
  },

  coverImage: {
    height: 165,
    width: '92%',
    borderRadius: Spacing.l,
    overflow: 'hidden',
  },

  profileContainer: {
    position: 'absolute',
    bottom: -30,
    height: 115,
    width: 115,
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 4,
    borderColor: '#fff',
    zIndex: 10,
    alignSelf: 'center',
    backgroundColor: AppColor.primaryBlue,
  },

  editText: {
    color: '#2A2A2A',
    fontFamily: PopinsFont.regular,
    fontSize: FontSizes.s,
    lineHeight: Spacing.l,
  },
  view2: {
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    borderRadius: Spacing.s,
    paddingVertical: 8,
    paddingHorizontal: 12,
    alignSelf: 'flex-end',
    margin: 12,
    gap: 5,
  },
  userName: {
    color: '#FFF',
    fontSize: 35,
    fontFamily: PopinsFont.medium,
    lineHeight: Spacing.xl,
  },
  profile: {
    height: 110,
    width: 110,
    borderRadius: 100,
    alignSelf: 'center',
  },
  name: {
    color: '#2A2A2A',
    fontFamily: PopinsFont.medium,
    fontSize: FontSizes.xl,
    textAlign: 'center',
    lineHeight: Spacing.xxl,
  },
  join: {
    color: '#6A6A6A',
    fontFamily: PopinsFont.regular,
    fontSize: FontSizes.s,
    textAlign: 'center',
    lineHeight: Spacing.l,
  },
  view1: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F7F7F7',
    borderColor: '#F1F1F1',
    borderWidth: 1,
    borderRadius: Spacing.s,
    paddingVertical: Spacing.xxs,
    paddingHorizontal: 10,
    alignSelf: 'flex-start',
    marginBottom: 80,
  },
  text1: {
    fontFamily: PopinsFont.regular,
    fontSize: FontSizes.s,
    lineHeight: Spacing.l,
    color: '#6A6A6A',
    marginLeft: 15,
  },
  img: {
    width: 27,
    height: 27,
    borderRadius: 100,
  },
  sideIcon: { height: 16, width: 16 },
  statusView: {
    // alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
    width: '92%',
    alignSelf: 'center',
  },
  content2: {
    flexDirection: 'row',
    paddingHorizontal: 5,
    paddingVertical: 10,
  },
  flatlistView: {
    flex: 1,
    backgroundColor: '#F1F1F1',
    borderTopLeftRadius: Spacing.xl,
    borderTopRightRadius: Spacing.xl,
    paddingHorizontal: Spacing.l,
    paddingTop: Spacing.l,
  },
  headingText: {
    fontFamily: PopinsFont.medium,
    fontSize: FontSizes.s,
    lineHeight: Spacing.l,
    color: AppColor.textColor,
    marginLeft: 5,
    marginBottom: 12,
  },
  flatlist: {
    flex: 1,
    position: 'relative',
  },
  footer: {
    backgroundColor: '#FFFFFF',
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginVertical: 10,
  },
  footerText: {
    color: '#6A6A6A',
    fontFamily: PopinsFont.regular,
    fontSize: FontSizes.s,
    lineHeight: FontSizes.l,
  },
  actionCard: {
    marginVertical: 5,
  },
  galleryView: {
    backgroundColor: '#F1F1F1',
    borderWidth: 1,
    borderColor: '#E1E1E1',
    borderRadius: 10,
    width: '90%',
    alignSelf: 'center',
    padding: 8,
    marginBottom: 12,
  },
  topBox: {
    backgroundColor: '#FFF',
    width: '100%',
    borderRadius: Spacing.s,
    padding: Spacing.s,
    height: 105,
    marginBottom: 8,
  },
  icon: { height: 10, width: 10 },
  iconView: {
    position: 'absolute',
    left: 0,
    top: '40%',
    zIndex: 1,
    backgroundColor: '#FFF',
    height: 28,
    width: 28,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E1E1E1',
    borderRadius: 100,
  },
  iconView1: {
    position: 'absolute',
    right: 0,
    top: '40%',
    zIndex: 1,
    backgroundColor: '#FFF',
    height: 28,
    width: 28,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E1E1E1',
    borderRadius: 100,
  },
  gallery: {
    color: '#2A2A2A',
    fontFamily: PopinsFont.medium,
    fontSize: FontSizes.s,
    lineHeight: Spacing.l,
    marginBottom: 8,
  },
  renderView: {
    flexDirection: 'row',
    gap: 5,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#E1E1E1',
    borderWidth: 1,
    paddingVertical: Spacing.xs,
    paddingHorizontal: Spacing.ms,
    borderRadius: Spacing.xl,
    marginRight: 5,
  },
  renderText: {
    color: '#989898',
    fontFamily: PopinsFont.medium,
    fontSize: FontSizes.m,
    lineHeight: Spacing.xl,
  },
  emptyView: {
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    gap: 10,
    height: 300,
    width: '100%',
  },
  text: {
    color: '#6A6A6A',
    fontFamily: PopinsFont.regular,
    fontSize: FontSizes.s,
    lineHeight: Spacing.l,
    textAlign: 'center',
  },
  contractorView: {
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    top: 45,
  },
  nameBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    alignSelf: 'center',
    marginBottom: 8,
  },
  joinView: {
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginBottom: 12,
  },
});
export default styles;
