import { StyleSheet, Platform, Dimensions } from 'react-native';
import { PopinsFont } from '../../../../helpers/Fonts';
import { Spacing } from '../../../../helpers/sizeHelper';
const { width, height } = Dimensions.get('window');
const MAP_HEIGHT = height * 0.35;
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  contentContainer: {
    paddingBottom: 20, // Extra space when keyboard opens
  },
  mainView: {
    borderWidth: 1,
    backgroundColor: '#F7F7F7',
    borderColor: '#E1E1E1',
    width: '90%',
    alignSelf: 'center',
    padding: 10,
    borderRadius: 20,
  },
  heading: {
    color: '#555555',
    fontFamily: PopinsFont.regular,
    fontSize: 14,
    textAlign: 'left',
  },
  mainView1: {
    marginVertical: 30,
    width: '95%',
    alignSelf: 'center',
  },
  subheading: {
    textAlign: 'left',
    alignSelf: 'flex-start',
    fontFamily: PopinsFont.regular,
    fontSize: 14,
    color: '#2A2A2A',
    marginLeft: 5,
  },
  subDescription: {
    fontSize: 14,
    color: '#666',
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  autocompleteContainer: {
    zIndex: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    // alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
  },
  searchInput: {
    height: 50,
    paddingHorizontal: 10,
    paddingTop: 10,
    fontSize: 16,
    backgroundColor: '#FFFFFF',
    color: '#6A6A6A',
    fontFamily: PopinsFont.regular,
    textAlignVertical: 'center',
    textAlign: 'left',
  },
  listView: {
    marginTop: 4,
    backgroundColor: '#FFF',
    zIndex: 9999,
  },
  row: {
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  separator: {
    height: 1,
    backgroundColor: 'transparent',
  },
  mapContainer: {
    height: MAP_HEIGHT,
    borderRadius: 10,
    overflow: 'hidden',
    position: 'relative',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    marginTop: 10,
    marginBottom: 2,
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  mapControls: {
    position: 'absolute',
    right: 12,
    top: 12,
    alignItems: 'center',
    backgroundColor: '#FFF',
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    height: 120,
    width: 40,
    justifyContent: 'center',
  },

  pinButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    top: 8,
  },
  controlButton: {
    width: 40,
    height: 60,
    justifyContent: 'center',
    alignItems: 'center',
  },
  scroll: {
    flex: 1,
    backgroundColor: 'transparent',
    top: Platform.OS === 'ios' ? 40 : 0,
  },
  input: {
    height: 50,
    paddingHorizontal: 10,
    paddingTop: 10,
    fontSize: 16,
    backgroundColor: '#F7F7F7',
    color: '#6A6A6A',
    fontFamily: PopinsFont.regular,
    textAlignVertical: 'center',
    textAlign: 'left',
    width: '80%',
  },
  miles: {
    fontFamily: PopinsFont.regular,
    color: '#2A2A2A',
    fontSize: 16,
    right: 5,
    lineHeight: Spacing.l,
  },
  bottomView: {
    backgroundColor: '#F1F1F1',
    width: '90%',
    alignSelf: 'center',
    padding: 10,
    borderRadius: 20,
    marginVertical: 10,
  },
  text: {
    color: '#6A6A6A',
    fontFamily: PopinsFont.regular,
    fontSize: 14,
    marginBottom: 5,
    lineHeight: Spacing.l,
  },
  inputView: {
    zIndex: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    // alignItems: 'center',
    borderWidth: 1,
    backgroundColor: '#F7F7F7',
    borderColor: '#E1E1E1',
    borderRadius: 10,
    alignItems: 'center',
    paddingHorizontal: 5,
    overflow: 'hidden',
  },
});
export default styles;
