import React from 'react';
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  ActivityIndicator,
} from 'react-native';
import { KeyboardAwareScrollView } from 'react-native-keyboard-aware-scroll-view';
import styles from './style';
import Button from '../../../../components/Button';
import { PopinsFont } from '../../../../helpers/Fonts';
import CustomOTPInput from '../../../../components/CustomOTP';
import Header from '../../../../components/Header';
import { FontSizes, Spacing } from '../../../../helpers/sizeHelper';
import AppColor from '../../../../helpers/AppColor';
const Design = props => {
  return (
    <View style={styles.Container}>
      <Header showBackIcon title={'Enable 2FA'} navigation={props.navigation} />

      <ScrollView
        showsHorizontalScrollIndicator={false}
        showsVerticalScrollIndicator={false}
        style={styles.scroll}
      >
        <KeyboardAwareScrollView>
          <View style={styles.content}>
            <Text style={styles.text}>
              Copy the secret code to your authentication app on your mobile
              device. Then paste the two-factor verification code generated by
              your app below.
              <TouchableOpacity>
                <Text style={styles.text1}>Learn more.</Text>
              </TouchableOpacity>
            </Text>
          </View>
          <View style={styles.view1}>
            <View style={styles.otpContainer}>
              <CustomOTPInput
                length={6}
                onChange={code => {
                  props.setOtp(code);
                }}
              />
            </View>
          </View>
        </KeyboardAwareScrollView>
      </ScrollView>

      <View style={styles.button}>
        <Button
          text={'Go Back'}
          color={'#404040'}
          fontFamily={PopinsFont.regular}
          fontSize={FontSizes.m}
          lineHeight={Spacing.xl}
          height={44}
          backgroundColor={'#F7F7F7'}
          borderWidth={1}
          borderColor={'#E1E1E1'}
          width={'49%'}
          borderRadius={Spacing.s}
          onPress={() => props.navigation.goBack()}
        />
        <Button
          text={props.isLoading ? '' : 'Save'}
          color={props.isLoading ? 'transparennt' : '#FFF'}
          fontFamily={PopinsFont.regular}
          fontSize={FontSizes.m}
          lineHeight={Spacing.xl}
          height={44}
          backgroundColor={'#009FD9'}
          borderWidth={1}
          borderColor={'#009FD9'}
          width={'49%'}
          borderRadius={Spacing.s}
          onPress={() => props.handleVerifyMFA()}
          rightIcon={
            props.isLoading ? (
              <ActivityIndicator size={'small'} color={AppColor.white} />
            ) : null
          }
        />
      </View>
    </View>
  );
};
export default Design;
