// show real app
export const SHOW_REAL_APP = 'SHOW_REAL_APP';
// save user location
export const SAVE_USER_LOCATION = 'SAVE_USER_LOCATION';
// save login info
export const SAVE_LOGIN_INFO = 'SAVE_LOGIN_INFO';
// user logout
export const USER_LOGOUT = 'USER_LOGOUT';
// reset Loading
export const RESET_ALL_LOADING = 'RESET_ALL_LOADING';
// update local user info
export const UPDATE_LOCAL_USER_INFO = 'UPDATE_LOCAL_USER_INFO';
// user signup
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_REQUEST_SUCCESS = 'SIGNUP_REQUEST_SUCCESS';
export const SIGNUP_REQUEST_FAILED = 'SIGNUP_REQUEST_FAILED';
// select role
export const SELECT_ROLE_REQUEST = 'SELECT_ROLE_REQUEST';
export const SELECT_ROLE_REQUEST_SUCCESS = 'SELECT_ROLE_REQUEST_SUCCESS';
export const SELECT_ROLE_REQUEST_FAILED = 'SELECT_ROLE_REQUEST_FAILED';
// accept Terms
export const ACCEPT_TERMS_REQUEST = 'ACCEPT_TERMS_REQUEST';
export const ACCEPT_TERMS_REQUEST_SUCCESS = 'ACCEPT_TERMS_REQUEST_SUCCESS';
export const ACCEPT_TERMS_REQUEST_FAILED = 'ACCEPT_TERMS_REQUEST_FAILED';
// create profile
export const CREATE_NEW_PROFILE_REQUEST = 'CREATE_NEW_PROFILE_REQUEST';
export const CREATE_NEW_PROFILE_SUCCESS = 'CREATE_NEW_PROFILE_SUCCESS';
export const CREATE_NEW_PROFILE_FAILED = 'CREATE_NEW_PROFILE_FAILED';
// onboard user
export const ONBOARD_USER_REQUEST = 'ONBOARD_USER_REQUEST';
export const ONBOARD_USER_REQUEST_SUCCESS = 'ONBOARD_USER_REQUEST_SUCCESS';
export const ONBOARD_USER_REQUEST_FAILED = 'ONBOARD_USER_REQUEST_FAILED';
// user login
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
// user forget password
export const FORGET_PASSWORD_REQUEST = 'FORGET_PASSWORD_REQUEST';
export const FORGET_PASSWORD_REQUEST_SUCCESS =
  'FORGET_PASSWORD_REQUEST_SUCCESS';
export const FORGET_PASSWORD_REQUEST_FAILED = 'FORGET_PASSWORD_REQUEST_FAILED';
// verify otp
export const VERIFY_OTP_REQUEST = 'VERIFY_OTP_REQUEST';
export const VERIFY_OTP_REQUEST_SUCCESS = 'VERIFY_OTP_REQUEST_SUCCESS';
export const VERIFY_OTP_REQUEST_FAILED = 'VERIFY_OTP_REQUEST_FAILED';
// reset password
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_REQUEST_SUCCESS = 'RESET_PASSWORD_REQUEST_SUCCESS';
export const RESET_PASSWORD_REQUEST_FAILED = 'RESET_PASSWORD_REQUEST_FAILED';
// reset password
export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST';
export const UPDATE_PASSWORD_REQUEST_SUCCESS =
  'UPDATE_PASSWORD_REQUEST_SUCCESS';
export const UPDATE_PASSWORD_REQUEST_FAILED = 'UPDATE_PASSWORD_REQUEST_FAILED';
// social login
export const SOCIAL_LOGIN_REQUEST = 'SOCIAL_LOGIN_REQUEST';
export const SOCIAL_LOGIN_REQUEST_SUCCESS = 'SOCIAL_LOGIN_REQUEST_SUCCESS';
export const SOCIAL_LOGIN_REQUEST_FAILED = 'GOOGLE_LOGIN_REQUEST_FAILED';
//create mfa token
export const CREATE_MFA_VERIFY_SETUP_REQUEST =
  'CREATE_MFA_VERIFY_SETUP_REQUEST';
export const CREATE_MFA_VERIFY_SETUP_REQUEST_SUCCESS =
  'CREATE_MFA_VERIFY_SETUP_REQUEST_SUCCESS';
export const CREATE_MFA_VERIFY_SETUP_REQUEST_FAILED =
  'CREATE_MFA_VERIFY_SETUP_REQUEST_FAILED';
// mfa setup
export const MFA_SETUP_REQUEST = 'MFA_SETUP_REQUEST';
export const MFA_SETUP_REQUEST_SUCCESS = 'MFA_SETUP_REQUEST_SUCCESS';
export const MFA_SETUP_REQUEST_FAILED = 'MFA_SETUP_REQUEST_FAILED';
// mfa verify setup
export const MFA_VERIFY_SETUP_REQUEST = 'MFA_VERIFY_SETUP_REQUEST';
export const MFA_VERIFY_SETUP_REQUEST_SUCCESS =
  'MFA_VERIFY_SETUP_REQUEST_SUCCESS';
export const MFA_VERIFY_SETUP_REQUEST_FAILED =
  'MFA_VERIFY_SETUP_REQUEST_FAILED';
// mfa verify
export const MFA_VERIFY_REQUEST = 'MFA_VERIFY_REQUEST';
export const MFA_VERIFY_REQUEST_SUCCESS = 'MFA_VERIFY_REQUEST_SUCCESS';
export const MFA_VERIFY_REQUEST_FAILED = 'MFA_VERIFY_REQUEST_FAILED';
// update user
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_REQUEST_SUCCESS = 'UPDATE_USER_REQUEST_SUCCESS';
export const UPDATE_USER_REQUEST_FAILED = 'UPDATE_USER_REQUEST_FAILED';
// revoke single session
export const REVOKE_SINGLE_SESSION_REQUEST = 'REVOKE_SINGLE_SESSION_REQUEST';
export const REVOKE_SINGLE_SESSION_REQUEST_SUCCESS =
  'REVOKE_SINGLE_SESSION_REQUEST_SUCCESS';
export const REVOKE_SINGLE_SESSION_REQUEST_FAILED =
  'REVOKE_SINGLE_SESSION_REQUEST_FAILED';
// revoke all sessions
export const REVOKE_ALL_SESSION_REQUEST = 'REVOKE_ALL_SESSION_REQUEST';

export const REVOKE_ALL_SESSION_REQUEST_SUCCESS =
  'REVOKE_ALL_SESSION_REQUEST_SUCCESS';
export const REVOKE_ALL_SESSION_REQUEST_FAILED =
  'REVOKE_ALL_SESSION_REQUEST_FAILED';
// revoke others sessions
export const REVOKE_OTHERS_SESSION_REQUEST = 'REVOKE_OTHERS_SESSION_REQUEST';

export const REVOKE_OTHERS_SESSION_REQUEST_SUCCESS =
  'REVOKE_OTHERS_SESSION_REQUEST_SUCCESS';
export const REVOKE_OTHERS_SESSION_REQUEST_FAILED =
  'REVOKE_OTHERS_SESSION_REQUEST_FAILED';
// verify email
export const VERIFY_EMAIL_REQUEST = 'VERIFY_EMAIL_REQUEST';
export const VERIFY_EMAIL_REQUEST_SUCCESS = 'VERIFY_EMAIL_REQUEST_SUCCESS';
export const VERIFY_EMAIL_REQUEST_FAILED = 'VERIFY_EMAIL_REQUEST_FAILED';
// get user data from api
export const GET_USER_DATA_REQUEST = 'GET_USER_DATA_REQUEST';
export const GET_USER_DATA_REQUEST_SUCCESS = 'GET_USER_DATA_REQUEST_SUCCESS';
export const GET_USER_DATA_REQUEST_FAILED = 'GET_USER_DATA_REQUEST_FAILED';
