export const ADD_CHAT = 'ADD_CHAT';
export const UPDATE_CHAT = 'UPDATE_CHAT';
export const SET_SELECTED_CHAT = 'SET_SELECTED_CHAT';
export const SET_MESSAGES = 'SET_MESSAGES';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const SET_TYPING_USER = 'SET_TYPING_USER';
export const SET_LOADING_CHATS = 'SET_LOADING_CHATS';
export const SET_LOADING_MESSAGES = 'SET_LOADING_MESSAGES';
export const SET_SELECTED_JOB_CHAT = 'SET_SELECTED_JOB_CHAT';
export const SET_SELECTED_CHAT_PERSON = 'SET_SELECTED_CHAT_PERSON';
export const DELETE_CHAT = 'DELETE_CHAT';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
// get all chats
export const GET_ALL_CHAT_REQUEST = 'GET_ALL_CHAT_REQUEST';
export const GET_ALL_CHAT_REQUEST_SUCCESS = 'GET_ALL_CHAT_REQUEST_SUCCESS';
export const GET_ALL_CHAT_REQUEST_FAILED = 'GET_ALL_CHAT_REQUEST_FAILED';
