// contractor earnings
export const GET_EARNINGS_REQUEST = 'GET_EARNINGS_REQUEST';
export const GET_EARNINGS_REQUEST_SUCCESS = 'GET_EARNINGS_REQUEST_SUCCESS';
export const GET_EARNINGS_REQUEST_FAILED = 'GET_EARNINGS_REQUEST_FAILED';
// contractor action items
export const ACTION_ITEMS_REQUEST = 'ACTION_ITEMS_REQUEST';
export const ACTION_ITEMS_REQUEST_SUCCESS = 'ACTION_ITEMS_REQUEST_SUCCESS';
export const ACTION_ITEMS_REQUEST_FAILED = 'ACTION_ITEMS_REQUEST_FAILED';
// contractor applied Jobs
export const GET_MY_JOBS_REQUEST = 'GET_MY_JOBS_REQUEST';
export const GET_MY_JOBS_REQUEST_SUCCESS = 'GET_MY_JOBS_REQUEST_SUCCESS';
export const GET_MY_JOBS_REQUEST_FAILED = 'GET_MY_JOBS_REQUEST_FAILED';
// Get jobs for bidding
export const GET_JOBS_FOR_CONTRACTOR_REQUEST =
  'GET_JOBS_FOR_CONTRACTOR_REQUEST';
export const GET_JOBS_FOR_CONTRACTOR_REQUEST_SUCCESS =
  'GET_JOBS_FOR_CONTRACTOR_REQUEST_SUCCESS';
export const GET_JOBS_FOR_CONTRACTOR_REQUEST_FAILED =
  'GET_JOBS_FOR_CONTRACTOR_REQUEST_FAILED';
// submit Bid on job
export const SUBMIT_BID_REQUEST = 'SUBMIT_BID_REQUEST';
export const SUBMIT_BID_REQUEST_SUCCESS = 'SUBMIT_BID_REQUEST_SUCCESS';
export const SUBMIT_BID_REQUEST_FAILED = 'SUBMIT_BID_REQUEST_FAILED';
// get submitted Bids
export const SUBMITTED_BIDS_REQUEST = 'SUBMITTED_BIDS_REQUEST';
export const SUBMITTED_BIDS_REQUEST_SUCCESS = 'SUBMITTED_BIDS_REQUEST_SUCCESS';
export const SUBMITTED_BIDS_REQUEST_FAILED = 'SUBMITTED_BIDS_REQUEST_FAILED';
// withdraw bid

export const WITHDRAW_BID_REQUEST = 'WITHDRAW_BID_REQUEST';
export const WITHDRAW_BID_REQUEST_SUCCESS = 'WITHDRAW_BID_REQUEST_SUCCESS';
export const WITHDRAW_BID_REQUEST_FAILED = 'WITHDRAW_BID_REQUEST_FAILED';
// use myBids screen in search screen
export const USE_BIDS_SCREEN = 'USE_BIDS_SCREEN';
// use myJobs screen in search screen
export const USE_MY_JOBS_SCREEN = 'USE_MY_JOBS_SCREEN';
// Get Due Jobs Today For Contractor
export const GET_JOBS_DUE_TODAY_FOR_CONTRACTOR_REQUEST =
  'GET_JOBS_DUE_TODAY_FOR_CONTRACTOR_REQUEST';
export const GET_JOBS_DUE_TODAY_FOR_CONTRACTOR_REQUEST_SUCCESS =
  'GET_JOBS_DUE_TODAY_FOR_CONTRACTOR_REQUEST_SUCCESS';
export const GET_JOBS_DUE_TODAY_FOR_CONTRACTOR_REQUEST_FAILED =
  'GET_JOBS_DUE_TODAY_FOR_CONTRACTOR_REQUEST_FAILED';
// Get Reviews
export const GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST';
export const GET_REVIEWS_REQUEST_SUCCESS = 'GET_REVIEWS_REQUEST_SUCCESS';
export const GET_REVIEWS_REQUEST_FAILED = 'GET_REVIEWS_REQUEST_FAILED';
// Get Notifications
export const GET_NOTIFICATIONS_REQUEST = 'GET_NOTIFICATIONS_REQUEST';
export const GET_NOTIFICATIONS_REQUEST_SUCCESS =
  'GET_NOTIFICATIONS_REQUEST_SUCCESS';
export const GET_NOTIFICATIONS_REQUEST_FAILED =
  'GET_NOTIFICATIONS_REQUEST_FAILED';
// get all sessions
export const GET_ALL_SESSIONS_REQUEST = 'GET_ALL_SESSIONS_REQUEST';
export const GET_ALL_SESSIONS_REQUEST_SUCCESS =
  'GET_ALL_SESSIONS_REQUEST_SUCCESS';
export const GET_ALL_SESSIONS_REQUEST_FAILED =
  'GET_ALL_SESSIONS_REQUEST_FAILED';

// get direct assigned bids/jobs
export const GET_DIRECT_ASSIGNED_BIDS_REQUEST =
  'GET_DIRECT_ASSIGNED_BIDS_REQUEST';
export const GET_DIRECT_ASSIGNED_BIDS_REQUEST_SUCCESS =
  'GET_DIRECT_ASSIGNED_BIDS_REQUEST_SUCCESS';
export const GET_DIRECT_ASSIGNED_BIDS_REQUEST_FAILED =
  'GET_DIRECT_ASSIGNED_BIDS_REQUEST_FAILED';
// get status of sstripe accoiunt
export const GET_STRIPE_ACCOUNT_STATUS_REQUEST =
  'GET_STRIPE_ACCOUNT_STATUS_REQUEST';
export const GET_STRIPE_ACCOUNT_STATUS_REQUEST_SUCCESS =
  'GET_STRIPE_ACCOUNT_STATUS_REQUEST_SUCCESS';
export const GET_STRIPE_ACCOUNT_STATUS_REQUEST_FAILED =
  'GET_STRIPE_ACCOUNT_STATUS_REQUEST_FAILED';
// get single job details
export const GET_SINGLE_JOB_DETAILS_REQUEST = 'GET_SINGLE_JOB_DETAILS_REQUEST';
export const GET_SINGLE_JOB_DETAILS_REQUEST_SUCCESS =
  'GET_SINGLE_JOB_DETAILS_REQUEST_SUCCESS';
export const GET_SINGLE_JOB_DETAILS_REQUEST_FAILED =
  'GET_SINGLE_JOB_DETAILS_REQUEST_FAILED';
// notification preferences
export const GET_NOTIFICATIONS_PREFERENCES_REQUEST =
  'GET_NOTIFICATIONS_PREFERENCES_REQUEST';
export const GET_NOTIFICATIONS_PREFERENCES_REQUEST_SUCCESS =
  'GET_NOTIFICATIONS_PREFERENCES_REQUEST_SUCCESS';
export const GET_NOTIFICATIONS_PREFERENCES_REQUEST_FAILED =
  'GET_NOTIFICATIONS_PREFERENCES_REQUEST_FAILED';
// update notification preferences
export const UPDATE_NOTIFICATIONS_PREFERENCES_REQUEST =
  'UPDATE_NOTIFICATIONS_PREFERENCES_REQUEST';
export const UPDATE_NOTIFICATIONS_PREFERENCES_REQUEST_SUCCESS =
  'UPDATE_NOTIFICATIONS_PREFERENCES_REQUEST_SUCCESS';
export const UPDATE_NOTIFICATIONS_PREFERENCES_REQUEST_FAILED =
  'UPDATE_NOTIFICATIONS_PREFERENCES_REQUEST_FAILED';
